FROM apache/superset:3.1.3

USER root
RUN pip install --no-cache-dir \
    "SQLAlchemy<2.0" \
    clickhouse-connect==0.6.8 \
    clickhouse-sqlalchemy==0.2.3

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER superset
